version: '3.9'

services:
  backend:
    contest: ./backend
  restart: always
  command: gunicorn backend.wsgi --bind 0.0.0.0:8000
  ports: "8000:8000"
  environment:
    - DB_HOST=db
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - SECRET_KEY=${DJANGO_SECRET_KEY}
    - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGINS}
  depends_on:
    - db

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react

volumes:
  postgres-data:
  react_build: