version: '3.9'

services:
  backend:
    build:
      context: ./backend
    restart: always
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=dbuser
      - DB_PASS=changeme
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=127.0.0.1
    depends_on:
      - db
    volumes:
      - static-data:/django/static
      - ./backend/.env:/django/.env:ro

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeme

  nginx:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - build-files:/usr/share/nginx/html
      - static-data:/usr/share/nginx/static

volumes:
  postgres-data:
  build-files:
  static-data: